export const CREATE_QUESTIONS = 'CREATE_QUESTIONS';
export const ANSWER_QUESTION = 'ANSWER_QUESTION';
export const SUBMIT_QUESTIONS = 'SUBMIT_QUESTIONS';
export const RESET_QUESTIONS = 'RESET_QUESTIONS';
